version: "3"

services:

  spotify-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes: 
      - ./server:/app
    ports: 
      - "3001:3001"
    tty: true
    environment:
      - DB_NAME=spotify
      - DB_PASSWORD=nirkahana8
      - DB_USER=root
      - DB_HOST=db
    networks: 
      - my-net
    depends_on: 
      - db
    restart: always

  # spotify-client:
  #   build: 
  #     context: ./client
  #     dockerfile: Dockerfile
  #   volumes: 
  #     - ./client:/usr/src/app/
  #   stdin_open: true
  #   ports: 
  #     - "3000:3000"
  #   tty: true
  #   networks: 
  #     - my-net
  #   depends_on: 
  #     - spotify-server
  
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "3306:3306"
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=nirkahana8
      - MYSQL_PASSWORD=nirkahana8
      - MYSQL_DATABASE=spotify
      - MYSQL_USER=root
    networks: 
      - my-net
    # volumes:
    #   - my-db:/var/lib/mysql

# volumes:
#   my-db:

networks:
  my-net:
    driver: bridge